DROP TABLE IF EXISTS grade;

CREATE TABLE grade (
  id INT(11) NOT NULL AUTO_INCREMENT,
  code VARCHAR(255) DEFAULT NULL,
  nbHeuresBase DECIMAL(10, 2) DEFAULT NULL,
  tauxBase DECIMAL(10, 2) DEFAULT NULL,
  PRIMARY KEY (id)
);
